all_atoms: true
atom_max_neighbors: 8
atom_radius: 5
batch_size: 8
c_alpha_max_neighbors: 24
cache_path: /home/dev/sw_cache/data
cache_scope: dataset
checkpoint_freq: 25
config: null
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: true
data_dir: /home/dev/sw_cache/data/full_pdb_dataset
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: /home/dev/sw_cache/data/full_pdb_embeddings/
inference_earlystop_goal: max
inference_steps: 20
limit_complexes: 0
log_dir: models
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 300
no_batch_norm: false
ns: 24
num_conformers: 1
num_conv_layers: 3
num_dataloader_workers: 4
num_workers: 2
nv: 6
pin_memory: false
project: superwater_train
receptor_radius: 15.0
remove_hs: true
restart_dir: null
restart_lr: null
run_name: large_pdbs_clustered
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sigma_embed_dim: 64
split_test: /home/dev/sw_cache/data/large_dataset_splits/test.txt
split_train: /home/dev/sw_cache/data/large_dataset_splits/train.txt
split_val: /home/dev/sw_cache/data/large_dataset_splits/val.txt
test_sigma_intervals: true
tr_sigma_max: 30.0
tr_sigma_min: 0.1
tr_weight: 1
train_inference_freq: null
use_ema: true
use_second_order_repr: false
val_inference_freq: null
w_decay: 0.0
wandb: false
wandb_entity: null
